spring:
  main:
    web-application-type: none

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
    open-in-view: false
    hibernate:
      ddl-auto: none
      multiTenancy: SCHEMA
      tenant_identifier_resolver: com.example.Partition_Test.ChunkTest.config.tenant.TenantIdentifierResolver
      multi_tenant_connection_provider: com.example.Partition_Test.ChunkTest.config.tenant.TenantConnectProvider

  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: admin
    driver-class: com.mysql.jdbc.Driver

  db-param:
    mixing-username: spring_batch
    electrode-username: sprout_db

  map:
    mixing:
      path: this is mixing
    electrode:
      path: this is electrorde


